### ISSUE TITLE
Saving words

### ISSUE THREAD

**Issue by Easybuoy** [nobioma1/describe-3-words#4]
If I try to save the last word, it saves the first one instead.

**Comment by haywhyze** [comment]
Do you mean it saves the first word or it hoists the saved word to the top?

**Comment by Easybuoy** [comment]
Oh, it moves the saved word to the top, I thought it saves the wrong one

**Comment by Easybuoy** [comment]
Closing this issue, because it's not really an issue, thanks for clarifying.
